import {
    StyledAccordion,
    StyledAccordionSummary,
} from '@/components/molecules/FilterItem/StyledFilterItem';
import { Skeleton } from '@mui/material';

const PseudoFilterList = () => {
    return (
        <div>
            <StyledAccordion>
                <StyledAccordionSummary
                    expandIcon={
                        <Skeleton
                            variant="rectangular"
                            width={'12px'}
                            height={'12px'}
                        />
                    }
                >
                    <Skeleton
                        variant="rectangular"
                        width={'60%'}
                        height={'24px'}
                    />
                </StyledAccordionSummary>
            </StyledAccordion>
            <StyledAccordion>
                <StyledAccordionSummary
                    expandIcon={
                        <Skeleton
                            variant="rectangular"
                            width={'12px'}
                            height={'12px'}
                        />
                    }
                >
                    <Skeleton
                        variant="rectangular"
                        width={'60%'}
                        height={'24px'}
                    />
                </StyledAccordionSummary>
            </StyledAccordion>
            <StyledAccordion>
                <StyledAccordionSummary
                    expandIcon={
                        <Skeleton
                            variant="rectangular"
                            width={'12px'}
                            height={'12px'}
                        />
                    }
                >
                    <Skeleton
                        variant="rectangular"
                        width={'60%'}
                        height={'24px'}
                    />
                </StyledAccordionSummary>
            </StyledAccordion>
            <StyledAccordion>
                <StyledAccordionSummary
                    expandIcon={
                        <Skeleton
                            variant="rectangular"
                            width={'12px'}
                            height={'12px'}
                        />
                    }
                >
                    <Skeleton
                        variant="rectangular"
                        width={'60%'}
                        height={'24px'}
                    />
                </StyledAccordionSummary>
            </StyledAccordion>
            <StyledAccordion>
                <StyledAccordionSummary
                    expandIcon={
                        <Skeleton
                            variant="rectangular"
                            width={'12px'}
                            height={'12px'}
                        />
                    }
                >
                    <Skeleton
                        variant="rectangular"
                        width={'60%'}
                        height={'24px'}
                    />
                </StyledAccordionSummary>
            </StyledAccordion>
            <StyledAccordion>
                <StyledAccordionSummary
                    expandIcon={
                        <Skeleton
                            variant="rectangular"
                            width={'12px'}
                            height={'12px'}
                        />
                    }
                >
                    <Skeleton
                        variant="rectangular"
                        width={'60%'}
                        height={'24px'}
                    />
                </StyledAccordionSummary>
            </StyledAccordion>
            <StyledAccordion>
                <StyledAccordionSummary
                    expandIcon={
                        <Skeleton
                            variant="rectangular"
                            width={'12px'}
                            height={'12px'}
                        />
                    }
                >
                    <Skeleton
                        variant="rectangular"
                        width={'60%'}
                        height={'24px'}
                    />
                </StyledAccordionSummary>
            </StyledAccordion>
            <StyledAccordion>
                <StyledAccordionSummary
                    expandIcon={
                        <Skeleton
                            variant="rectangular"
                            width={'12px'}
                            height={'12px'}
                        />
                    }
                >
                    <Skeleton
                        variant="rectangular"
                        width={'60%'}
                        height={'24px'}
                    />
                </StyledAccordionSummary>
            </StyledAccordion>
            <StyledAccordion>
                <StyledAccordionSummary
                    expandIcon={
                        <Skeleton
                            variant="rectangular"
                            width={'12px'}
                            height={'12px'}
                        />
                    }
                >
                    <Skeleton
                        variant="rectangular"
                        width={'60%'}
                        height={'24px'}
                    />
                </StyledAccordionSummary>
            </StyledAccordion>
        </div>
    );
};
export default PseudoFilterList;
