export enum FacilityBenefit {
    parking = 'Паркинг',
    elevator = 'Лифт',
    pool = 'Бассейн',
    Concierge = 'Консьерж',
    recreationArea = 'Зона отдыха',
    kidPlayground = 'Детская площадка',
    closedTerritory = 'Закрытая территория',
    privateBeach = 'Собственный пляж',
    panoramicWindows = 'Панорамные окна',
    houseTerritory = 'Придомовая территория',
    houseShops = 'Придомовые магазины',
    playground = 'Спортивная площадка',
    tennisCourts = 'Теннисные корты',
    tennisAcademy = 'Теннисная академия',
    managementCompany = 'Управляющая компания',
    centralCommunications = 'Центральные коммуникации',
    school = 'Школа в шаговой доступности',
    seaView = 'Вид на море',
    videoIntercom = 'Видеодомофон',
    videoSurveillance = 'Видеонаблюдение',
    freightElevator = 'Грузовой лифт',
    kindergarten = 'Детский сад в шаговой доступности',
    cafesRestaurants = 'Кафе и рестораны в шаговой доступности',
    commercialSquares = 'Коммерчиские площади',
    congressHall = 'Конгресс-холл',
}
